FROM ros:humble

# 1. Ottimizza gli layer apt-get
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*  # Pulisci la cache per ridurre l'immagine

# 2. Aggiungi dipendenze ROS comuni (opzionale ma utile)
RUN apt-get update && apt-get install -y \
    ros-humble-rqt* \
    ros-humble-turtlesim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/ros_workspace

CMD ["bash"]