FROM ros:humble


RUN apt update -y && apt install -y wget
RUN apt install -y ros-humble-example-interfaces
RUN sudo apt install python3-colcon-common-extensions

RUN apt install -y ros-humble-rqt

WORKDIR /root/ros_workspace
